export const stock = [
  {
    img: "woori.svg",
    name: "우리금융지주",
    unit: "₩",
    price: "2873.47",
    flag: "1.09",
    percentage: "0.04",
  },
  {
    img: "kor.svg",
    name: "KOSPI",
    unit: "₩",
    price: "2873.47",
    flag: "1.09",
    percentage: "0.04",
  },
  {
    img: "kor.svg",
    name: "KOSDAQ",
    unit: "₩",
    price: "731.88",
    flag: "6.48",
    percentage: "0.89",
  },
  {
    img: "kor.svg",
    name: "KOSPI200",
    unit: "₩",
    price: "731.88",
    flag: "6.48",
    percentage: "0.89",
  },
  {
    img: "kor.svg",
    name: "KOSPI200",
    unit: "₩",
    price: "731.88",
    flag: "6.48",
    percentage: "0.89",
  },
  {
    img: "usa.svg",
    name: "DOW",
    unit: "$",
    price: "1160.48",
    flag: "2.81",
    percentage: "2.81",
  },
  {
    img: "usa.svg",
    name: "NASDAQ",
    unit: "$",
    price: "18708.43",
    flag: "6.48",
    percentage: "0.89",
  },
  {
    img: "usa.svg",
    name: "S&P 500",
    unit: "$",
    price: "5884.19",
    flag: "148.28",
    percentage: "3.26",
  },
  {
    img: "jpy.svg",
    name: "NIKKEI 225",
    unit: "¥",
    price: "5884.19",
    flag: "148.28",
    percentage: "3.26",
  },
  {
    img: "cn.svg",
    name: "SSEC",
    unit: "",
    price: "5884.19",
    flag: "-148.28",
    percentage: "-3.26",
  },
  {
    img: "hk.svg",
    name: "HSCE",
    unit: "",
    price: "5884.19",
    flag: "-148.28",
    percentage: "-3.26",
  },
];

export const stockDupDummy = [...stock, ...stock, ...stock, ...stock, ...stock];
